import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {buildSkillExposureAnalysis, buildSkillExposureRow, rankSkillPatterns, selectSkillBaseline} from '../src/domain/skill-exposure';
import {bayesianPrevalence} from '../src/domain/bayesian-prevalence';
import type {Contingency} from '../src/domain/bayesian-prevalence';
import type {Exposure, Snapshot} from '../src/domain/types';
import type {SkillsData} from '../src/search/skills';

const snapshot: Snapshot = JSON.parse(readFileSync('public/data/occupations.json', 'utf8'));
const skills: SkillsData = JSON.parse(readFileSync('public/data/skills.json', 'utf8'));
const close = (actual: number | null, expected: number) => assert(actual !== null && Math.abs(actual - expected) <= Math.max(1e-14, Math.abs(expected) * 1e-10), `${actual} != ${expected}`);
function fixture() {
  const roles = [{code: 'a', importance: [5, 2, null, 1]}, {code: 'b', importance: [1, 2, 3, 1]}, {code: 'c', importance: [4, 1, null, 1]}, {code: 'd', importance: [2, 3, 4, 1]}, {code: 'e', importance: [2, 1, 2, 1]}, {code: 'all', importance: [5, 5, 5, 5]}];
  const mapped: [Exposure | null, string[]][] = [['Very high', ['a', 'a', 'b']], ['Very high', ['c']], ['Low', ['d']], ['Moderate', ['e']], [null, ['all']], ['High', ['missing']]];
  const data: SkillsData = {...skills, skills: skills.skills.slice(0, 4), roles};
  const snap: Snapshot = {...snapshot, occupations: mapped.map(([exposure, codes], i) => ({...snapshot.occupations[0], code: String(i), exposure, roles: codes.map(code => ({...snapshot.occupations[0].roles[0], code}))}))};
  return {snap, data};
}

test('one BLS observation, unique role means, inclusive threshold, skill-specific denominators and unknown exposure exclusion', () => {
  const {snap, data} = fixture(), analysis = buildSkillExposureAnalysis(snap, data);
  const rows = analysis.rows.filter(row => row.category === 'Very high');
  assert.deepEqual(rows.map(row => row.counts), [[2, 0, 0, 2], [0, 2, 1, 1], [1, 0, 1, 1], [0, 2, 0, 2]]);
  assert.deepEqual(rows.map(row => row.overallKnown), [4, 4, 3, 4]);
  assert.deepEqual(rows.map(row => row.overallImportant), [2, 1, 2, 0]);
  assert.deepEqual(rows.map(row => row.ratio), [2, 0, 1.5, null]);
  assert.deepEqual(rows.map(row => row.direction), ['more', 'less', 'more', 'equal']);
  rows.forEach((row, i) => close(row.difference, [50, -25, 100 / 3, 0][i]));
  assert.equal(rows[2].selectedKnown, 1);
  assert.equal(analysis.eligibleOccupations, 4);
  assert.equal(analysis.unknownExposure, 1);
  assert.equal(analysis.noRatings, 1);
  assert.deepEqual(analysis.categoryCounts, {Low: 1, Moderate: 1, High: 0, 'Very high': 2});
  const high = analysis.rows.filter(row => row.category === 'High');
  assert(high.every(row => row.ratio === null && row.difference === null && row.evidence === null));
});

test('ranking orders infinity, finite, zero, undefined; ties resolve by skill ID without mutating input', () => {
  const {snap, data} = fixture(), rows = buildSkillExposureAnalysis(snap, data).rows.filter(row => row.category === 'Very high');
  assert.deepEqual(rankSkillPatterns(rows).map(row => row.skill.id), [data.skills[0].id, data.skills[2].id, data.skills[1].id, data.skills[3].id]);
  const tied = rows.map(row => ({...row, ratio: Infinity})).reverse();
  assert.deepEqual(rankSkillPatterns(tied).map(row => row.skill.id), data.skills.map(skill => skill.id).sort());
  assert.deepEqual(rows.map(row => row.skill.id), data.skills.map(skill => skill.id));
});

// Independent oracle generated by the parent with SciPy 1.10.1, quad + brentq:
// F_D(z) = integral beta.pdf(u,a+1,b+1) * beta.sf(u-z,c+1,d+1) du,
// split at interior z,z+1; epsabs/epsrel=1e-11; brentq xtol=1e-12.
const references: {counts: Contingency; probabilityMore: number; meanDifference: number; interval: [number, number]}[] =
  JSON.parse(readFileSync('tests/fixtures/bayesian-reference.json', 'utf8'));
test('Beta model matches independent quadrature for balanced, sparse, constant, extreme and snapshot examples', () => {
  for (const reference of references) {
    const result = bayesianPrevalence(reference.counts)!;
    assert(Math.abs(result.probabilityMore - reference.probabilityMore) <= 0.012, `probability ${reference.counts}`);
    close(result.meanDifference, reference.meanDifference);
    const tolerance = reference.counts.reduce((a, b) => a + b) >= 400 ? 0.2 : 1;
    result.interval.forEach((value, i) => assert(Math.abs(value - reference.interval[i]) <= tolerance, `interval ${reference.counts}: ${result.interval} vs ${reference.interval}`));
    assert(result.interval[0] < result.interval[1]);
    assert.deepEqual(result.selectedPosterior, reference.counts.slice(0, 2).map(n => n + 1));
    assert.deepEqual(result.otherPosterior, reference.counts.slice(2).map(n => n + 1));
  }
});

test('draws repeat exactly, do not mutate inputs, and obey group-swap symmetry', () => {
  for (const reference of references) {
    const counts: Contingency = [...reference.counts];
    Object.freeze(counts);
    const first = bayesianPrevalence(counts)!;
    assert.deepEqual(bayesianPrevalence(counts), first);
    const swap = bayesianPrevalence([counts[2], counts[3], counts[0], counts[1]])!;
    close(first.probabilityMore + swap.probabilityMore, 1);
    close(first.meanDifference, -swap.meanDifference);
    close(first.interval[0], -swap.interval[1]);
    close(first.interval[1], -swap.interval[0]);
    assert.deepEqual(counts, reference.counts);
  }
});

test('constant outcomes retain a labeled model; missing groups are unavailable and invalid counts fail', () => {
  const zero = bayesianPrevalence([0, 3, 0, 7])!;
  const all = bayesianPrevalence([3, 0, 7, 0])!;
  assert(zero.constantOutcome && all.constantOutcome);
  assert(zero.meanDifference > 0 && all.meanDifference < 0);
  assert.equal(bayesianPrevalence([10, 10, 10, 10])!.constantOutcome, false);
  assert.equal(bayesianPrevalence([0, 0, 3, 7]), null);
  assert.equal(bayesianPrevalence([3, 7, 0, 0]), null);
  assert.equal(bayesianPrevalence([0, 0, 0, 0]), null);
  for (const invalid of [-1, 1.5, NaN, Infinity, -Infinity, Number.MAX_SAFE_INTEGER]) {
    assert.throws(() => bayesianPrevalence([invalid, 2, 3, 4]));
  }
  const {snap, data} = fixture();
  const empty = buildSkillExposureAnalysis({...snap, occupations: []}, data);
  assert.equal(empty.rows.length, 16);
  assert(empty.rows.every(row => row.ratio === null && row.evidence === null));
});

test('snapshot has 140 comparisons and recognizable rare-skill counts; filtering and ordering preserve model evidence', () => {
  const analysis = buildSkillExposureAnalysis(snapshot, skills);
  assert.equal(analysis.comparisons, 140);
  assert.equal(analysis.rows.length, 140);
  assert.equal(analysis.eligibleOccupations, 772);
  assert.equal(analysis.noRatings, 59);
  const overall = rankSkillPatterns(analysis.rows.filter(row => row.category === 'Very high'));
  assert.equal(overall[0].skill.name, 'Technology Design');
  close(overall[0].ratio, (5 / 170) / (6 / 659));
  const programming = overall.find(row => row.skill.name === 'Programming')!;
  close(programming.ratio, 518 / 175);
  close(programming.difference, 100 * (19 / 175 - 19 / 518));
  assert.equal(programming.evidence!.meanDifference.toFixed(1), '7.3');
  const ranked = rankSkillPatterns(overall.map(row => selectSkillBaseline(row, 'rest')));
  assert.equal(ranked.length, 35);
  assert.equal(ranked[0].skill.name, 'Programming');
  assert.equal(ranked[0].ratio, Infinity);
  assert.deepEqual(ranked[0].counts, [19, 156, 0, 343]);
  assert.equal(ranked[1].skill.name, 'Technology Design');
  assert.deepEqual(ranked[1].counts, [5, 165, 1, 488]);
  close(ranked[1].ratio, (5 / 170) / (1 / 489));
  assert.equal(ranked.filter(row => row.skill.name.includes('Technology'))[0].evidence, analysis.rows.find(row => row.category === 'Very high' && row.skill.name === 'Technology Design')!.restEvidence);
  const {snap, data} = fixture();
  const before = JSON.stringify({snap, data});
  const original = buildSkillExposureAnalysis(snap, data);
  const reordered = buildSkillExposureAnalysis({...snap, occupations: [...snap.occupations].reverse()}, {...data, roles: [...data.roles].reverse()});
  assert.deepEqual(reordered, original);
  assert.equal(JSON.stringify({snap, data}), before);
  const reversedSkills = buildSkillExposureAnalysis(snap, {...data, skills: [...data.skills].reverse(), roles: data.roles.map(role => ({...role, importance: [...role.importance].reverse()}))});
  for (const row of original.rows) assert.deepEqual(reversedSkills.rows.find(other => other.skill.id === row.skill.id && other.category === row.category), row);
});


test('overall includes selected; observed arithmetic and weighted posterior preserve disjoint counts across repeated toggles', () => {
  const counts: Contingency = [15, 10, 15, 60];
  const overall = buildSkillExposureRow(skills.skills[0], 'Very high', counts);
  close(overall.selectedPrevalence, 0.6);
  close(overall.overallPrevalence, 0.3);
  close(overall.ratio, 2);
  close(overall.difference, 30);
  const rest = selectSkillBaseline(overall, 'rest');
  close(rest.baselinePrevalence, 0.2);
  close(rest.ratio, 3);
  close(rest.difference, 40);
  assert.deepEqual(overall.counts, [15, 10, 15, 60]);
  assert.deepEqual(overall.evidence!.selectedPosterior, [16, 11]);
  assert.deepEqual(overall.evidence!.otherPosterior, [16, 61]);
  close(overall.evidence!.meanDifference, 0.75 * 100 * (16 / 27 - 16 / 77));
  overall.evidence!.interval.forEach((value, i) => close(value, 0.75 * rest.evidence!.interval[i]));
  assert.equal(overall.evidence!.probabilityMore, rest.evidence!.probabilityMore);
  let switched = overall;
  for (let i = 0; i < 5; i++) {
    switched = selectSkillBaseline(selectSkillBaseline(switched, 'rest'), 'overall');
    assert.deepEqual(switched, overall);
  }
});

test('overall weighted posterior matches scaled independent quadrature references', () => {
  for (const reference of references) {
    const row = buildSkillExposureRow(skills.skills[0], 'Very high', reference.counts);
    const scale = (reference.counts[2] + reference.counts[3]) / reference.counts.reduce((a, b) => a + b);
    assert(Math.abs(row.evidence!.probabilityMore - reference.probabilityMore) <= 0.012);
    close(row.evidence!.meanDifference, scale * reference.meanDifference);
    const tolerance = reference.counts.reduce((a, b) => a + b) >= 400 ? 0.2 : 1;
    row.evidence!.interval.forEach((value, i) => assert(Math.abs(value - scale * reference.interval[i]) <= scale * tolerance));
  }
});

test('overall boundaries retain valid observed self-comparisons but never invent a prior-only comparison', () => {
  const cases: [Contingency, number | null, number | null, string, boolean][] = [
    [[0, 3, 0, 7], null, 0, 'equal', true], [[3, 0, 7, 0], 1, 0, 'equal', true],
    [[2, 3, 0, 5], 2, 20, 'more', true], [[0, 5, 2, 3], 0, -20, 'less', true],
    [[3, 2, 0, 0], 1, 0, 'equal', false], [[0, 5, 0, 0], null, 0, 'equal', false],
    [[0, 0, 3, 7], null, null, 'unavailable', false], [[0, 0, 0, 0], null, null, 'unavailable', false],
  ];
  for (const [counts, ratio, difference, direction, modeled] of cases) {
    const row = buildSkillExposureRow(skills.skills[0], 'Very high', counts);
    assert.equal(row.ratio, ratio);
    if (difference === null) assert.equal(row.difference, null); else close(row.difference, difference);
    assert.equal(row.direction, direction);
    assert.equal(row.evidence !== null, modeled);
  }
  assert.equal(buildSkillExposureRow(skills.skills[0], 'Very high', [0, 3, 0, 7]).evidence!.constantOutcome, true);
  assert.equal(buildSkillExposureRow(skills.skills[0], 'Very high', [3, 0, 7, 0]).evidence!.constantOutcome, true);
  assert.equal(selectSkillBaseline(buildSkillExposureRow(skills.skills[0], 'Very high', [2, 3, 0, 5]), 'rest').ratio, Infinity);
});

test('baseline-specific ranking can reverse when per-skill group coverage differs', () => {
  const a = buildSkillExposureRow({...skills.skills[0], id: 'A'}, 'Very high', [80, 10, 1, 9]);
  const b = buildSkillExposureRow({...skills.skills[0], id: 'B'}, 'Very high', [2, 8, 9, 81]);
  assert.deepEqual(rankSkillPatterns([a, b]).map(row => row.skill.id), ['B', 'A']);
  assert.deepEqual(rankSkillPatterns([a, b].map(row => selectSkillBaseline(row, 'rest'))).map(row => row.skill.id), ['A', 'B']);
});
