import {useEffect,useState} from 'react';
import type {Exposure,Snapshot} from '../domain/types';
import {exposureExplanation,loadAiContext,type AiContextData} from '../domain/ai-context';

export function ExposureContext({category}:{category:Exposure|null}){
 return <div className="exposure-context"><p className="category-explanation">{category?exposureExplanation[category]:'No published exposure category is available for this occupation. Its relative exposure cannot be inferred from the missing value.'}</p><p>Relative exposure combines how AI capabilities relate to the work and recorded AI interactions linked to similar tasks. Those interactions do not establish worker adoption. The categories do not distinguish assistance from automation.</p><p className="evidence-timeframe"><strong>Evidence timeframe</strong><br/>Published August 27, 2026. Theoretical sources reflect capabilities from 2020 and 2023; observed-use evidence is mainly from 2024–2025. This is not a measurement of today’s AI capabilities.</p><p className="source-line"><a href="https://www.bls.gov/emp/publications/ai-exposure-categories.htm">BLS exposure method and source dates</a></p></div>;
}

type LoadState={status:'loading'}|{status:'error'}|{status:'ready';data:AiContextData};
export function AiOutlookContext({snapshot,code}:{snapshot:Snapshot;code:string}){
 const [state,setState]=useState<LoadState>({status:'loading'}),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const controller=new AbortController();setState({status:'loading'});loadAiContext(snapshot,controller.signal).then(data=>{if(!controller.signal.aborted)setState({status:'ready',data});}).catch(()=>{if(!controller.signal.aborted)setState({status:'error'});});return()=>controller.abort();},[snapshot,attempt]);
 const notes=state.status==='ready'?state.data.notes.filter(n=>n.code===code):[];
 return <section className="ai-outlook-context" aria-labelledby="ai-outlook-heading"><h3 id="ai-outlook-heading">AI in BLS employment outlook notes</h3><p className="ai-outlook-scope">These are BLS assumptions about an occupation’s share of staffing within the listed industries in the 2025–2035 projections. A decreasing share can occur even when total employment grows. These notes do not explain the exposure category or measure total job losses caused by AI.</p>
 {state.status==='loading'&&<p role="status">Loading optional BLS outlook notes… Published figures and search remain available.</p>}
 {state.status==='error'&&<div role="alert"><p>The optional BLS outlook notes could not load. This is not evidence that the source has no AI note for this occupation.</p><button className="secondary no-print" onClick={()=>{setState({status:'loading'});setAttempt(n=>n+1);}}>Retry outlook notes</button></div>}
 {state.status==='ready'&&(notes.length?<><p className="hint">Source wording for BLS {code}. {notes.length} {notes.length===1?'note':'notes'} explicitly {notes.length===1?'mentions':'mention'} AI or a related term.</p><ul className="ai-outlook-notes">{notes.map(note=><li key={note.row}><h4>{note.industryCode==='TE1000'?'Scope':'Industry-specific scope'}: {note.industry}</h4><p className="source-line">Industry {note.industryCode} · {note.title} · BLS {note.code}</p><blockquote>{note.note}</blockquote><p className="source-line"><a href={state.data.source.url}>BLS Table 1.12, Excel row {note.row}</a> · Projected {state.data.startYear}–{state.data.endYear}</p></li>)}</ul></>:<p className="ai-outlook-absence">No note explicitly mentioning AI, artificial intelligence, machine learning, or large language models was found for this BLS occupation in this BLS table. This does not mean AI has no effect; the table does not document every factor for every occupation and industry.</p>)}
 <p className="source-line"><a href="https://www.bls.gov/emp/tables/factors-affecting-occupational-utilization.htm">BLS factors affecting occupational utilization</a> · 2025–2035 projections. Notes retain the source’s industry scope; “all industries” rows are identified separately. Specialist O*NET roles share their broader BLS occupation’s notes.</p></section>;
}
