import type{Ref}from'react';
import type{Occupation,Snapshot}from'../domain/types';
const exposureNote='This category compares occupations under the published method. It does not estimate your chance of losing a job.';
const pct=(n:number|null)=>n===null?'Unavailable':`${n>0?'+':''}${n.toFixed(1)}%`;
const openings=(n:number|null)=>n===null?'Unavailable':n.toLocaleString('en-US');
interface Props {compared:Occupation[];compare:string[];data:Snapshot;comparisonHeading:Ref<HTMLHeadingElement>;updateComparison:(codes:string[],message:string)=>void;download:()=>void;share:()=>void;brief:()=>void}
export default function OccupationComparison({compared,compare,data,comparisonHeading,updateComparison,download,share,brief}:Props){return (
<section className="comparison" aria-labelledby="comparison-heading"><div className="comparison-heading"><h2 id="comparison-heading" tabIndex={-1} ref={comparisonHeading}>Compare occupations</h2><div className="comparison-controls"><span>{compared.length} of 3</span><button className="text-button no-print" onClick={()=>updateComparison([],'Comparison cleared.')}>Clear comparison</button></div></div><p className="hint no-print">Search and confirm another occupation to add it. Use Remove occupation below any title to remove it. On a small screen, scroll the table horizontally.</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Occupation comparison; scroll horizontally if needed"><table><caption>Published U.S. occupational information · {data.release.bls}</caption><thead><tr><th scope="col">Published measure</th>{compared.map(o=><th scope="col" key={o.code}>{o.title}<span className="table-code">BLS {o.code}</span><button className="secondary remove-occupation no-print" onClick={()=>updateComparison(compare.filter(c=>c!==o.code),`${o.title} removed from comparison.`)} aria-label={`Remove ${o.title}`}><span aria-hidden="true">× </span>Remove occupation</button></th>)}</tr></thead><tbody><tr><th scope="row">Relative AI exposure</th>{compared.map(o=><td key={o.code}>{o.exposure||'AI exposure data unavailable'}</td>)}</tr><tr><th scope="row">Projected employment change</th>{compared.map(o=><td key={o.code}>{pct(o.growth)}<small>{o.startYear}–{o.endYear}</small></td>)}</tr><tr><th scope="row">Annual average openings</th>{compared.map(o=><td key={o.code}>{openings(o.annualOpenings)}<small>{o.startYear}–{o.endYear} · includes replacement needs</small></td>)}</tr><tr><th scope="row">Statistical scope</th>{compared.map(o=><td key={o.code}>BLS occupation {o.code}{o.roles.some(r=>r.broader)&&<small>Includes specialist roles; figures cover the whole BLS occupation.</small>}</td>)}</tr></tbody></table></div><p className="comparison-note">{exposureNote} Projected employment change is an overall outlook, not a causal estimate of AI’s effects.</p><div className="actions no-print"><button className="secondary" onClick={download}>Download comparison CSV</button><button className="text-button" onClick={brief}>Download comparison brief</button><button className="text-button" onClick={()=>window.print()}>Print / save PDF</button><button className="text-button" onClick={share}>Share comparison</button></div></section>
);}
