import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {createHash} from 'node:crypto';
import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TEST_URL||'http://127.0.0.1:4173/work-and-ai/';
const out=resolve(process.env.OUTPUT_DIR||'verification/local');await mkdir(out,{recursive:true});
const report={date:new Date().toISOString(),base,checks:[],requests:[],errors:[]};
const browser=await chromium.launch({headless:true});report.browser=browser.version();
const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(15000);
context.on('request',r=>report.requests.push({url:r.url(),method:r.method(),body:r.postData()}));
page.on('pageerror',e=>report.errors.push(String(e)));const logs=[];page.on('console',m=>logs.push(m.text()));
const check=(name)=>{report.checks.push(name);console.log(name);};
const title=page.getByRole('searchbox',{name:'Job title'});
async function search(query,name){await title.fill(query);await page.locator('#title-status').filter({hasText:/suggestion|No close matches|could describe/}).waitFor();const candidate=page.getByRole('button',{name:new RegExp('^'+name+' BLS')});await candidate.waitFor();await candidate.press('Enter');await page.waitForFunction(()=>document.activeElement?.id==='occupation-heading');}
try{
 await page.goto(base);await title.waitFor();await page.waitForFunction(()=>!document.querySelector('#job-title').disabled);
 assert(!report.requests.some(r=>/\/models\/|\/runtime\/|\/semantic\/|worker-/.test(r.url)));check('Initial ordinary app loads no semantic assets');
 await search('registered nurse','Registered Nurses');await page.getByRole('button',{name:'Add to comparison',exact:true}).click();
 await search('pharmacist','Pharmacists');await page.getByRole('button',{name:'Add to comparison',exact:true}).click();
 await search('Chief Sustainability Officer','Chief Sustainability Officers');assert.match(await page.locator('.scope-note').innerText(),/broader BLS occupation/);await page.getByRole('button',{name:'Add to comparison',exact:true}).click();
 await search('electrician','Electricians');await page.getByRole('button',{name:'Add to comparison',exact:true}).click();await page.getByText('Your comparison already has three occupations.',{exact:false}).waitFor();
 assert.equal(await page.locator('.comparison thead th').count(),4);await page.getByRole('button',{name:'Remove Pharmacists',exact:true}).click();assert.equal(await page.locator('.comparison thead th').count(),3);
 await search('pharmacist','Pharmacists');await page.getByRole('button',{name:'Add to comparison',exact:true}).click();check('Keyboard confirmation, specialist scope, compare limit, remove and re-add');
 await page.getByRole('button',{name:'Share comparison',exact:true}).click();const shared=page.url();assert.match(shared,/#roles=/);assert(!shared.includes('pharmacist'));await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.comparison thead th').length===4);check('Three-role public code/release share survives refresh');
 await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true});
 const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download comparison CSV',exact:true}).click();const download=await downloadPromise;await download.saveAs(resolve(out,'comparison.csv'));const csv=await readFile(resolve(out,'comparison.csv'),'utf8');assert(csv.includes('29-1141')&&csv.includes('29-1051')&&csv.includes('11-1011'));check('Actual browser CSV download saved with all three canonical occupations');
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('.no-print:visible').count(),0);const geometry=await page.locator('table').evaluate(e=>({x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right,width:innerWidth}));assert(geometry.x>=0&&geometry.right<=geometry.width);await page.pdf({path:resolve(out,'comparison.pdf'),preferCSSPageSize:true,printBackground:true});check('Real Chromium PDF generated using production print stylesheet');await page.emulateMedia({media:'screen'});
 await page.goto(base+'#roles=29-1141&release=unavailable-old-release');await page.reload();await page.getByRole('alert').filter({hasText:/release/i}).waitFor();check('Unavailable historical release disclosed');
 await page.goto(shared);await page.reload();await page.waitForFunction(()=>document.querySelectorAll('.comparison thead th').length===4);
 await title.fill('registered nurse');await page.locator('#title-status').filter({hasText:/suggestion|No close matches|could describe/}).waitFor();await page.getByRole('button',{name:'None of these fit',exact:false}).click();assert.equal(await title.inputValue(),'');
 const sentinel='WAI_PRIVATE_SENTINEL_20260910';await page.getByRole('textbox',{name:'A few specific responsibilities, in English'}).fill('I dispense prescribed medicines and advise patients about their safe use. '+sentinel);
 const beforeHeading=await page.locator('#occupation-heading').innerText();await page.getByRole('button',{name:'Search by meaning',exact:true}).click();await page.locator('.refine [role=status],.refine [role=alert]').filter({hasText:/Enhanced matching finished|could not|timed out/}).first().waitFor({timeout:125000});assert.equal(await page.getByRole('alert').count(),0);assert.equal(await page.locator('#occupation-heading').innerText(),beforeHeading);await page.getByRole('button',{name:/^Pharmacists BLS/}).waitFor();check('Rejected exact title releases constraint; meaning search preserves confirmed selection');
 const privateExport=page.waitForEvent('download');await page.getByRole('button',{name:'Download comparison CSV',exact:true}).click();await(await privateExport).saveAs(resolve(out,'privacy-comparison.csv'));assert(!(await readFile(resolve(out,'privacy-comparison.csv'),'utf8')).includes(sentinel));assert(!JSON.stringify(report.requests).includes(sentinel));assert(!logs.some(s=>s.includes(sentinel)));assert(report.requests.every(r=>new URL(r.url).origin===new URL(base).origin));assert(report.requests.every(r=>r.method==='GET'));check('Synthetic private sentinel absent from URLs, request bodies, logs and saved CSV; same-origin GETs only');
 const mobile=await context.newPage({viewport:{width:390,height:844}});await mobile.setViewportSize({width:390,height:844});await mobile.goto(shared);await mobile.waitForFunction(()=>document.querySelectorAll('.comparison thead th').length===4);assert(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await mobile.screenshot({path:resolve(out,'mobile.png'),fullPage:true});const scroll=mobile.locator('.table-scroll');assert(await scroll.evaluate(e=>e.scrollWidth>e.clientWidth));await scroll.focus();await mobile.keyboard.press('End');await mobile.getByRole('button',{name:'Remove Pharmacists',exact:true}).click();assert.equal(await mobile.locator('.comparison thead th').count(),3);check('390px real viewport, no page overflow, scrollable labelled table and usable removal');await mobile.close();
 // Fresh browser context provides a genuinely empty cache on the same origin.
 const diagnosticContext=await browser.newContext({viewport:{width:1280,height:900}});const diagnostic=await diagnosticContext.newPage();await diagnostic.goto(base+'diagnostics.html');await diagnostic.getByRole('button',{name:'Run worker verification',exact:true}).click();await diagnostic.waitForFunction(()=>document.querySelector('#verification-output')?.textContent?.includes('"boundaries"')||document.querySelector('#verification-output')?.textContent?.includes('"failure"'),{},{timeout:180000});report.diagnostics=JSON.parse(await diagnostic.locator('#verification-output').textContent());assert(!report.diagnostics.failure);assert.equal(report.diagnostics.cacheBefore.length,0);assert.deepEqual(report.diagnostics.race,['A cancelled','B cancelled','C resolved']);assert.equal(report.diagnostics.boundaries[0].result,'accepted');assert.match(report.diagnostics.boundaries[1].result,/257/);check('Fresh-context cold/warm worker, all faults, race and token boundaries');
 await diagnostic.reload();await diagnostic.getByRole('button',{name:'Run worker verification',exact:true}).click();await diagnostic.waitForFunction(()=>document.querySelector('#verification-output')?.textContent?.includes('"boundaries"')||document.querySelector('#verification-output')?.textContent?.includes('"failure"'),{},{timeout:180000});report.revisit=JSON.parse(await diagnostic.locator('#verification-output').textContent());assert(report.revisit.cacheBefore.some(x=>x.entries.some(url=>url.endsWith('.onnx'))));assert(!report.revisit.real.workerRequests.some(r=>/\/models\/|\/runtime\//.test(r.url)&&r.transfer>300));check('Actual repeat visit uses pinned model/runtime cache');
 await diagnostic.getByRole('combobox',{name:'App failure scenario'}).selectOption('download');await diagnostic.getByRole('searchbox',{name:'Job title'}).fill('pharmacist');await diagnostic.locator('#title-status').filter({hasText:/suggestion|No close matches|could describe/}).waitFor();await diagnostic.getByRole('button',{name:/^Pharmacists BLS/}).click();await diagnostic.getByRole('button',{name:'Add to comparison',exact:true}).click();await diagnostic.getByRole('button',{name:'None of these fit',exact:false}).click();await diagnostic.getByRole('textbox',{name:'A few specific responsibilities, in English'}).fill('I design roads and bridges.');await diagnostic.getByRole('button',{name:'Search by meaning',exact:true}).click();await diagnostic.getByRole('alert').waitFor({timeout:30000});await diagnostic.getByRole('searchbox',{name:'Job title'}).fill('registered nurse');await diagnostic.locator('#title-status').filter({hasText:/suggestion|No close matches|could describe/}).waitFor();await diagnostic.getByRole('button',{name:/^Registered Nurses BLS/}).waitFor();assert.equal(await diagnostic.locator('.comparison thead th').count(),2);check('Blocked model request preserves selection/comparison and ordinary search');await diagnosticContext.close();
 assert.equal(report.errors.length,0);report.status='PASS';
}catch(error){report.status='FAIL';report.failure=String(error);await page.screenshot({path:resolve(out,'failure.png'),fullPage:true}).catch(()=>{});console.error(error);process.exitCode=1;}
finally{report.artifacts={};for(const name of ['comparison.csv','privacy-comparison.csv','comparison.pdf','desktop.png','mobile.png']){try{const b=await readFile(resolve(out,name));report.artifacts[name]={bytes:b.length,sha256:createHash('sha256').update(b).digest('hex')};}catch{}}await writeFile(resolve(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');await browser.close();console.log(JSON.stringify({status:report.status,checks:report.checks.length,out,failure:report.failure}));}
