import{useEffect,useRef,useState}from'react';
import type{Candidate,Lexicon,Occupation,SearchOutcome,Snapshot}from'./domain/types';
import{SearchEngine}from'./search/engine';import{comparisonCsv}from'./export/csv';import{readShare,shareHash}from'./state/share';
import type{SemanticClient,DiagnosticFault}from'./semantic/client';
const base=import.meta.env.BASE_URL;
const exposureNote='This category compares occupations under the published method. It does not estimate your chance of losing a job.';
const pct=(n:number|null)=>n===null?'Unavailable':`${n>0?'+':''}${n.toFixed(1)}%`;
const openings=(n:number|null)=>n===null?'Unavailable':n.toLocaleString('en-US');
const empty:SearchOutcome={state:'none',candidates:[],message:'',exact:false};
export default function App({diagnosticFault='none'}:{diagnosticFault?:DiagnosticFault}={}){
 const[data,setData]=useState<Snapshot|null>(null),[engine,setEngine]=useState<SearchEngine|null>(null),[loadError,setLoadError]=useState('');
 const[query,setQuery]=useState(''),[outcome,setOutcome]=useState(empty),[searched,setSearched]=useState(false),[refine,setRefine]=useState(false),[description,setDescription]=useState('');
 const[selected,setSelected]=useState<Candidate|null>(null),[compare,setCompare]=useState<string[]>([]),[notice,setNotice]=useState(''),[shareWarning,setShareWarning]=useState('');
 const[semanticStatus,setSemanticStatus]=useState(''),[busy,setBusy]=useState(false),[semanticError,setSemanticError]=useState('');
 const client=useRef<SemanticClient|null>(null),generation=useRef(0),resultHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{let active=true;Promise.all([fetch(base+'data/occupations.json').then(r=>{if(!r.ok)throw Error('data');return r.json();}),fetch(base+'data/lexicon.json').then(r=>{if(!r.ok)throw Error('titles');return r.json();})]).then(([snapshot,lexicon]:[Snapshot,Lexicon])=>{if(!active)return;if(snapshot.release.id!==lexicon.release)throw Error('release mismatch');setData(snapshot);setEngine(new SearchEngine(snapshot,lexicon));const shared=readShare(location.hash,snapshot);setCompare(shared.codes);setShareWarning(shared.warning);if(shared.codes.length)setSelected({code:shared.codes[0]});}).catch(()=>{if(active)setLoadError('The occupational reference could not load. Please reload this page to retry.');});return()=>{active=false;client.current?.dispose();};},[]);
 useEffect(()=>{if(!engine)return;generation.current++;if(busy){client.current?.cancel();setBusy(false);setSemanticStatus('');}const timer=setTimeout(()=>{if(query.trim()){setOutcome(engine.title(query));setSearched(true);}else{setOutcome(empty);setSearched(false);}},100);return()=>clearTimeout(timer);},[query,engine]);
 const current=data?.occupations.find(o=>o.code===selected?.code),role=current?.roles.find(r=>r.code===selected?.roleCode)||current?.roles[0];
 const compared=compare.map(code=>data?.occupations.find(o=>o.code===code)).filter(Boolean)as Occupation[];
 async function meaning(){if(!engine||busy||!description.trim())return;const id=++generation.current;setBusy(true);setSemanticError('');setSemanticStatus('Preparing enhanced matching…');try{if(!client.current){const{SemanticClient}=await import('./semantic/client');client.current=new SemanticClient(setSemanticStatus,diagnosticFault,diagnosticFault==='hang'?1500:120000);}const result=await client.current.search(description);if(id!==generation.current)return;setOutcome(engine.hybrid(query,description,result.evidence));setSearched(true);setSemanticStatus('Enhanced matching finished. Confirm a suggestion against the source description.');}catch(e){if(id===generation.current){setSemanticError(e instanceof Error?e.message:'Enhanced matching is unavailable.');setSemanticStatus('');}}finally{if(id===generation.current)setBusy(false);}}
 function choose(candidate:Candidate){generation.current++;client.current?.cancel();setBusy(false);setSelected(candidate);setNotice('');setTimeout(()=>resultHeading.current?.focus(),0);}
 function addComparison(){if(!current||compare.includes(current.code))return;if(compare.length===3){setNotice('Your comparison already has three occupations. Remove one to add another.');return;}setCompare([...compare,current.code]);setNotice('Added to comparison.');}
 function download(){if(!data)return;const rows=compared.length?compared:current?[current]:[];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([comparisonCsv(rows,data.release)],{type:'text/csv;charset=utf-8'}));a.download='work-and-ai-comparison.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setNotice('CSV prepared with published values, definitions, and sources.');}
 async function share(){if(!data)return;const codes=compare.length?compare:current?[current.code]:[];const hash=shareHash(codes,data.release.id);history.replaceState(null,'',location.pathname+hash);try{await navigator.clipboard.writeText(location.href);setNotice('Link copied. It contains only public occupation codes and the data release.');}catch{setNotice('The address bar now contains your share link. Copy it to share these occupations.');}}
 return <><header className="masthead"><a className="wordmark" href={base}>Work <span>&amp;</span> AI</a><span className="context">U.S. occupational data</span></header><main>
 <section className="intro no-print"><p className="eyebrow">An occupational reference</p><h1>Find the occupation.<br/>Explore the evidence.</h1><p className="lead">Explore published AI exposure and employment projections for U.S. occupations.</p></section>
 <section className="search-section no-print" aria-labelledby="search-heading"><h2 id="search-heading" className="section-label">01 / Find your occupation</h2><form onSubmit={e=>{e.preventDefault();if(engine){setOutcome(engine.title(query));setSearched(true);}}}><label htmlFor="job-title">Job title</label><div className="search-line"><input id="job-title" type="search" placeholder="For example, electrical engineer" value={query} onChange={e=>setQuery(e.target.value)} maxLength={160} disabled={!engine} autoComplete="off"/><button className="primary" disabled={!engine}>Find occupation <span aria-hidden="true">↗</span></button></div><p className="hint">Use an English title. You’ll confirm the occupation before viewing its figures.</p></form>
 {!engine&&!loadError&&<p role="status">Loading the occupational reference…</p>}{loadError&&<p role="alert">{loadError}</p>}
 {searched&&<div className="suggestions"><h3>Which occupation best describes your work?</h3><p role="status" aria-live="polite">{outcome.message}{outcome.candidates.length>0&&` ${outcome.candidates.length} ${outcome.candidates.length===1?'suggestion':'suggestions'}.`}</p><ol className="candidate-list">{outcome.candidates.map(candidate=>{const o=data!.occupations.find(o=>o.code===candidate.code)!;const r=o.roles.find(r=>r.code===candidate.roleCode)||o.roles[0];return <li key={o.code}><button className="candidate" onClick={()=>choose(candidate)}><span className="candidate-top"><strong>{r?.title||o.title}</strong><span className="code">BLS {o.code} <span aria-hidden="true">↗</span></span></span><span className="candidate-description">{(candidate.excerpt||r?.description||'A published BLS occupational result.').slice(0,300)}{(candidate.excerpt||r?.description||'').length>300?'…':''}</span><span className="attribution">{r?`O*NET® ${r.code} ${candidate.excerptKind==='task'?`task ${candidate.taskId}`:'description'} / `:''}{r?.broader?`Published figures cover the broader BLS occupation: ${o.title}`:o.title}</span></button></li>;})}</ol><button className="text-button" onClick={()=>{generation.current++;client.current?.cancel();setBusy(false);setQuery('');setOutcome(empty);setSearched(false);setRefine(true);setSemanticStatus('Previous title cleared. Describe the work you want to match.');}}>None of these fit — describe your work</button></div>}
 {!refine&&engine&&<button className="text-button refine-trigger" onClick={()=>setRefine(true)}>Can’t find your title? Describe your work</button>}
 {refine&&<div className="refine"><h3>Describe your work</h3><label htmlFor="responsibilities">A few specific responsibilities, in English</label><textarea id="responsibilities" rows={3} value={description} maxLength={1000} onChange={e=>{generation.current++;client.current?.cancel();setBusy(false);setDescription(e.target.value);setSemanticStatus('');}} placeholder="What do you make, analyze, maintain, teach, or support?"/><p className="hint">Keep it short: up to 1,000 characters and 256 model tokens (word pieces). Enhanced matching runs on your device. First use downloads about 52 MB of model, runtime, and index assets. Your text stays in this browser. Your browser may cache files; later visits may download them again.</p><button className="secondary" disabled={busy||!description.trim()} onClick={meaning}>{busy?'Matching…':semanticError?'Retry search by meaning':'Search by meaning'}</button>{busy&&<button className="text-button" onClick={()=>{generation.current++;client.current?.cancel();setBusy(false);setSemanticStatus('Cancelled. Ordinary title search remains available.');}}>Cancel</button>}<p role="status" className="hint">{semanticStatus}</p>{semanticError&&<p role="alert" className="error">{semanticError} Ordinary title search and your comparison remain available.</p>}</div>}
 </section>
 {shareWarning&&<p role="alert" className="notice">{shareWarning}</p>}
 {current&&data&&<article className="occupation" aria-labelledby="occupation-heading"><p className="eyebrow">02 / Confirmed occupation · BLS {current.code}</p><h2 id="occupation-heading" tabIndex={-1} ref={resultHeading}>{current.title}</h2>{role&&<><p className="description">{role.description}</p><p className="source-line">Description: <a href={role.source}>O*NET® {role.code} — {role.title}</a>, {data.release.onet}.</p>{role.broader&&<p className="scope-note">The description above is for <strong>{role.title}</strong>. The published figures below cover the broader BLS occupation, <strong>{current.title}</strong>. They were not measured separately for this specialist role.</p>}</>}
 <div className="metrics"><section><h3>AI exposure</h3><p className="stat">{current.exposure||'Data unavailable'}</p><p className="metric-label">{current.exposure?'Published relative exposure category':'AI exposure data unavailable'}</p><p>{exposureNote}</p><p className="source-line">BLS exposure categories · {data.release.bls}</p></section><section><h3>Employment outlook</h3><p className="stat">{pct(current.growth)}</p><p className="metric-label">Projected employment change, {current.startYear}–{current.endYear}</p><p>Overall employment projections reflect many factors. This change is not an estimate of AI’s effect.</p>{current.annualOpenings!==null&&<p className="openings"><strong>{openings(current.annualOpenings)}</strong> annual average openings, {current.startYear}–{current.endYear}. Openings include replacement needs as well as growth; they are not all new jobs.</p>}</section></div>
 <div className="actions no-print"><button className="secondary" onClick={addComparison} disabled={compare.includes(current.code)}>{compare.includes(current.code)?'In comparison':'Add to comparison'}</button><button className="text-button" onClick={download}>Download CSV</button><button className="text-button" onClick={()=>window.print()}>Print / save PDF</button><button className="text-button" onClick={share}>Share public link</button></div>
 </article>}
 {compared.length>0&&data&&<section className="comparison" aria-labelledby="comparison-heading"><div className="comparison-heading"><h2 id="comparison-heading">Compare occupations</h2><span>{compared.length} of 3</span></div><p className="hint no-print">Search and confirm another occupation to add it. On a small screen, scroll the table horizontally.</p><div className="table-scroll" tabIndex={0} role="region" aria-label="Occupation comparison; scroll horizontally if needed"><table><caption>Published U.S. occupational information · {data.release.bls}</caption><thead><tr><th scope="col">Published measure</th>{compared.map(o=><th scope="col" key={o.code}>{o.title}<span className="table-code">BLS {o.code}</span><button className="text-button no-print" onClick={()=>setCompare(compare.filter(c=>c!==o.code))} aria-label={`Remove ${o.title}`}>Remove</button></th>)}</tr></thead><tbody><tr><th scope="row">Relative AI exposure</th>{compared.map(o=><td key={o.code}>{o.exposure||'AI exposure data unavailable'}</td>)}</tr><tr><th scope="row">Projected employment change</th>{compared.map(o=><td key={o.code}>{pct(o.growth)}<small>{o.startYear}–{o.endYear}</small></td>)}</tr><tr><th scope="row">Annual average openings</th>{compared.map(o=><td key={o.code}>{openings(o.annualOpenings)}<small>{o.startYear}–{o.endYear} · includes replacement needs</small></td>)}</tr><tr><th scope="row">Statistical scope</th>{compared.map(o=><td key={o.code}>BLS occupation {o.code}{o.roles.some(r=>r.broader)&&<small>Includes specialist roles; figures cover the whole BLS occupation.</small>}</td>)}</tr></tbody></table></div><p className="comparison-note">{exposureNote} Projected employment change is an overall outlook, not a causal estimate of AI’s effects.</p><div className="actions no-print"><button className="secondary" onClick={download}>Download comparison CSV</button><button className="text-button" onClick={()=>window.print()}>Print / save PDF</button><button className="text-button" onClick={share}>Share comparison</button></div></section>}
 {notice&&<p role="status" className="notice no-print">{notice}</p>}
 <section className="methodology"><details><summary>Sources and interpretation</summary><div className="method-body"><h3>What the exposure category measures</h3><p>BLS groups occupations by their relative exposure across five external measures. Three consider how AI capabilities relate to work; two use observed AI interactions mapped to occupational tasks or activities. Those interactions do not establish that workers in that occupation used AI at work.</p><p>The categories do not distinguish automation from assistance. They are not probabilities of replacement, adoption forecasts, wage forecasts, or demonstrated productivity benefits. BLS normalizes source measures and imputes some missing inputs before grouping occupations. This app uses the published category unchanged.</p><h3>The evidence has a date</h3><p>The BLS release is dated August 27, 2026. Its theoretical sources reflect capabilities from 2020 and 2023, no later than mid-2023. Observed-use evidence is mainly from 2024–2025. A 2026 publication date does not mean today’s model capabilities were measured. Much of the evidence concerns language models and early users of particular products.</p><h3>The unit is an occupation, not a person</h3><p>Job duties differ across employers, locations, and individuals. These are U.S. estimates. English-language availability does not make them representative of another country. Published occupational requirements do not establish your skills, deficits, or learning needs. Matching and these explanations are app responsibilities, separate from the upstream research.</p><p>Projections describe an expected long-term employment path under the source’s assumptions, not an observed change or a range of possible outcomes. The source supplies no occupation-level confidence interval here.</p><h3>Matching and privacy</h3><p>Titles and aliases suggest occupations for you to confirm. Optional MiniLM matching retrieves reference descriptions locally; it never creates or changes statistics. Matching evaluation uses a small provisional set of authored examples, without independent expert validation. Your title and responsibilities are not included in shared links or exports. GitHub serves the static app and model files and may keep access logs.</p><h3>Source records</h3><ul><li><a href="https://www.bls.gov/emp/publications/ai-exposure-categories.htm">BLS exposure method and 2025–2035 workbook</a></li><li><a href="https://www.bls.gov/emp/classifications-crosswalks/nem-onet-to-soc-crosswalk.xlsx">BLS O*NET-to-National Employment Matrix crosswalk</a></li><li><a href="https://www.onetcenter.org/database.html">O*NET® 31.0 Database</a></li><li><a href="https://github.com/lstehlik2809/work-and-ai/blob/main/METHODOLOGY.md">App methodology, matching evaluation, and limitations</a></li></ul></div></details></section>
 <footer><p>Work &amp; AI <span className="footer-rule">/</span> U.S. occupational reference</p>{data&&<p className="source-line">{data.release.bls} · {data.release.onet} · Snapshot retrieved {data.release.retrieved.slice(0,10)}.</p>}<p className="attribution">Includes information from the O*NET® 31.0 Database by the U.S. Department of Labor, Employment and Training Administration (USDOL/ETA), used under <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>. O*NET® is a trademark of USDOL/ETA. Work &amp; AI has selected, combined, and indexed this information. USDOL/ETA has not approved, endorsed, or tested these modifications.</p><p className="print-sources">Statistics: https://www.bls.gov/emp/ind-occ-matrix/ai-exposure-categories.xlsx<br/>Descriptions: https://www.onetcenter.org/database.html<br/>Methodology: https://github.com/lstehlik2809/work-and-ai/blob/main/METHODOLOGY.md</p></footer>
 </main></>;
}
